// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWbwrIXbw_Twt9a10UwJ6xWkb9CJuNbgk',
    appId: '1:463111247842:web:1d77773a0e8a9fb1e28bbb',
    messagingSenderId: '463111247842',
    projectId: 'notes-app-bc726',
    authDomain: 'notes-app-bc726.firebaseapp.com',
    storageBucket: 'notes-app-bc726.appspot.com',
    measurementId: 'G-1S3N0FW5KG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOx2k3cpPWkgjDkNHUyzyJqI1Z8RNxXU4',
    appId: '1:463111247842:android:7426709815c1a7a7e28bbb',
    messagingSenderId: '463111247842',
    projectId: 'notes-app-bc726',
    storageBucket: 'notes-app-bc726.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGgEoODb9MXxKq_oWzsa7RUK5uDGWqzN8',
    appId: '1:463111247842:ios:a987c8ec2c5e3b32e28bbb',
    messagingSenderId: '463111247842',
    projectId: 'notes-app-bc726',
    storageBucket: 'notes-app-bc726.appspot.com',
    iosClientId:
        '463111247842-drosaodbfvfgj86r98nnhtaf3bsimigp.apps.googleusercontent.com',
    iosBundleId: 'com.example',
  );
}
